name = "r2-image-host"
main = "src/worker.js"
compatibility_date = "2026-08-19"

[vars]
R2_PUBLIC_DOMAIN = "https://image.surl.vip"

# KV 命名空间绑定s
[[kv_namespaces]]
binding = "INDEXES_KV"
id = "91708a20351047818cdf04384ea298ac"
preview_id = "91708a20351047818cdf04384ea298ac"

# R2 存储桶绑定
[[r2_buckets]]
binding = "bucket-binding"
bucket_name = "image-r2"


[site]
bucket = "src/static"

